version: "3.7"

services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database


volumes:
  db_data:
    driver: local
